### PR TITLE
Port GPUImageTransformFilter.

### PR DESCRIPTION
**Pull request by jonan**
**Note:** This is not my code, but I found it [here](https://github.com/leonrd/android-gpuimage), tested it, and think is useful.

Added new filter to perform transformations

### CODE REVIEW

**Comment by wasabeef** [comment]
@jonan 

sorry.. confilicts..

**Comment by jonan** [comment]
rebased

**Comment by wasabeef** [comment]
@jonan 

Great!

**Comment by wasabeef** [comment]
It will be released after a few days.

**Comment by wasabeef** [comment]
@jonan 

Released 1.4.0 :shipit:

**Pull request merged**
