### PR TITLE
Fixing GPUImageChromaKeyBlendFilter

### PR DESCRIPTION
**Pull request by badjano**
Fixed GPUImageChromaKeyBlendFilter based on iOS version, now it is a chroma key filter.

### CODE REVIEW

**Comment by Alfarache** [comment]
@badjano, did this fix the chroma key filter?  I see that the shader code is the same as the iOS version, but did it actually work for you?  I am getting no luck running the sample app with your updated filter code.

**Comment by badjano** [comment]
Yes @Alfarache, I have tested it and is working perfectly for me, just as it is in iOS, did you use my fork? I don't know if it has been merged to the main project yet

**Comment by Alfarache** [comment]
@badjano, I am using your fork and I am testing with the included sample app, which looks like it should work.  I replaced the overlay image with one that has a pure green background with a red and a blue circle. When I select the chroma key filter, there is no overlay image, just the background image.  If I select any other blend filter, the image that I created is visible and being filtered.  I am running this on a Samsung s4 with Android 4.4, if that matters.

Thanks again
chroma

**Comment by badjano** [comment]
@Alfarache I may be wrong, but it should work the opposite of what you are expecting, point the camera to something green and it will reveal your image. What you are trying to do is more easily accomplished just by putting an image with alpha channel on top of the camera image.

**Comment by Alfarache** [comment]
@badjano:   You are correct.  I had the filter layers reversed in my head, so I was expecting the opposite.

Thanks for your help!

**Comment by badjano** [comment]
@Alfarache No problem! :)

**Comment by wasabeef** [comment]
thanks.

Works confirmation.

**Pull request merged**
